### ISSUE TITLE
Traceback assertion error when replicating git repo

### ISSUE THREAD

**Issue by tcorbettclark** [tcorbettclark/file-replicator#7]
**Describe the bug**
Crashes out when replicating a git repo and making changes.

**To Reproduce**
1. Setup replication waiting for changes of a folder containing a git repo.
2. Make change, git add, git commit
3. See error:
```
Traceback (most recent call last): 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/bin/file-replicator", line 11, in <module> 
    sys.exit(main()) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/file_replicator/cli.py", line 96, in main 
    while replicate_files_on_change(src_dir, copy_file): 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/file_replicator/lib.py", line 101, in replicate_files_on_change 
    copy_file(os.path.join(path, filename)) 
  File "/home/tcorbettclark/.local/share/virtualenvs/inf-ice-docker/lib/python3.6/site-packages/file_replicator/lib.py", line 56, in copy_file 
    assert os.path.isfile(src_filename) 
AssertionError 
```

**Expected behavior**
Replication keeps going

**Comment by tcorbettclark** [comment]
This may be more related to ephemeral files being created by an editor. They are created, noticed by file-replicator, but removed before file-replicator has a chance to copy them.
